"""criar_tabela_ordens

Revision ID: 731158807e73
Revises: fb5cfb303d92
Create Date: 2026-10-09 14:32:40.526612

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '731158807e73'
down_revision: Union[str, Sequence[str], None] = 'fb5cfb303d92'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ordens',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('numero_ordem', sa.String(length=50), nullable=False),
    sa.Column('descricao', sa.String(length=255), nullable=False),
    sa.Column('operacao', sa.String(length=20), nullable=False),
    sa.Column('centro_trabalho', sa.String(length=100), nullable=False),
    sa.Column('horas_programadas', sa.Float(), nullable=False),
    sa.Column('data_programada', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('usuario_criador_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['usuario_criador_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ordens_centro_trabalho'), 'ordens', ['centro_trabalho'], unique=False)
    op.create_index(op.f('ix_ordens_data_programada'), 'ordens', ['data_programada'], unique=False)
    op.create_index(op.f('ix_ordens_id'), 'ordens', ['id'], unique=False)
    op.create_index(op.f('ix_ordens_numero_ordem'), 'ordens', ['numero_ordem'], unique=True)
    op.create_index(op.f('ix_ordens_status'), 'ordens', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ordens_status'), table_name='ordens')
    op.drop_index(op.f('ix_ordens_numero_ordem'), table_name='ordens')
    op.drop_index(op.f('ix_ordens_id'), table_name='ordens')
    op.drop_index(op.f('ix_ordens_data_programada'), table_name='ordens')
    op.drop_index(op.f('ix_ordens_centro_trabalho'), table_name='ordens')
    op.drop_table('ordens')
    # ### end Alembic commands ###
